// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipesApp.DAL.Context;

namespace RecipesApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220602154702_mg1")]
    partial class mg1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("CategoryRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            CategoriesId = 4
                        },
                        new
                        {
                            RecipesId = 1,
                            CategoriesId = 11
                        },
                        new
                        {
                            RecipesId = 2,
                            CategoriesId = 7
                        },
                        new
                        {
                            RecipesId = 2,
                            CategoriesId = 12
                        },
                        new
                        {
                            RecipesId = 3,
                            CategoriesId = 10
                        },
                        new
                        {
                            RecipesId = 4,
                            CategoriesId = 3
                        },
                        new
                        {
                            RecipesId = 5,
                            CategoriesId = 8
                        },
                        new
                        {
                            RecipesId = 6,
                            CategoriesId = 6
                        });
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("IngredientRecipe");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 1
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 2
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 3
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 4
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 5
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 6
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 7
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 8
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 9
                        },
                        new
                        {
                            RecipesId = 1,
                            IngredientsId = 10
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 11
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 2
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 12
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 13
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 14
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 15
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 8
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 17
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 18
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 19
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 20
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 21
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 22
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 23
                        },
                        new
                        {
                            RecipesId = 2,
                            IngredientsId = 24
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 25
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 26
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 27
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 28
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 29
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 30
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 31
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 32
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 33
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 34
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 35
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 36
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 37
                        },
                        new
                        {
                            RecipesId = 3,
                            IngredientsId = 38
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 10
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 39
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 40
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 41
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 42
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 43
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 44
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 45
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 46
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 47
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 48
                        },
                        new
                        {
                            RecipesId = 4,
                            IngredientsId = 49
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 50
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 39
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 51
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 52
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 53
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 54
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 55
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 56
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 57
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 5
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 58
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 59
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 60
                        },
                        new
                        {
                            RecipesId = 5,
                            IngredientsId = 61
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 10
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 62
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 5
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 40
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 63
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 64
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 44
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 65
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 66
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 67
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 68
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 69
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 70
                        },
                        new
                        {
                            RecipesId = 6,
                            IngredientsId = 71
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RecipesApp.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Salads"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Italian"
                        });
                });

            modelBuilder.Entity("RecipesApp.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameIngredient")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NameIngredient")
                        .IsUnique()
                        .HasFilter("[NameIngredient] IS NOT NULL");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameIngredient = "fresh parsley"
                        },
                        new
                        {
                            Id = 2,
                            NameIngredient = "olive oil"
                        },
                        new
                        {
                            Id = 3,
                            NameIngredient = "fresh oregano leaves"
                        },
                        new
                        {
                            Id = 4,
                            NameIngredient = "red wine vinegar"
                        },
                        new
                        {
                            Id = 5,
                            NameIngredient = "garlic"
                        },
                        new
                        {
                            Id = 6,
                            NameIngredient = "salt"
                        },
                        new
                        {
                            Id = 7,
                            NameIngredient = "rede pepper flakes"
                        },
                        new
                        {
                            Id = 8,
                            NameIngredient = "ground black pepper"
                        },
                        new
                        {
                            Id = 9,
                            NameIngredient = "whole chicken"
                        },
                        new
                        {
                            Id = 10,
                            NameIngredient = "onion"
                        },
                        new
                        {
                            Id = 11,
                            NameIngredient = "pancetta or salt pork"
                        },
                        new
                        {
                            Id = 12,
                            NameIngredient = "beef chuck"
                        },
                        new
                        {
                            Id = 13,
                            NameIngredient = "kosher salt"
                        },
                        new
                        {
                            Id = 14,
                            NameIngredient = "celery"
                        },
                        new
                        {
                            Id = 15,
                            NameIngredient = "carrot"
                        },
                        new
                        {
                            Id = 17,
                            NameIngredient = "tomato paste"
                        },
                        new
                        {
                            Id = 18,
                            NameIngredient = "bay leaf"
                        },
                        new
                        {
                            Id = 19,
                            NameIngredient = "white wine"
                        },
                        new
                        {
                            Id = 20,
                            NameIngredient = "yellow onions"
                        },
                        new
                        {
                            Id = 21,
                            NameIngredient = "rigatoni"
                        },
                        new
                        {
                            Id = 22,
                            NameIngredient = "fresh marjoram leaves"
                        },
                        new
                        {
                            Id = 23,
                            NameIngredient = "cayenne pepper"
                        },
                        new
                        {
                            Id = 24,
                            NameIngredient = "freshly grated Parmigiano-Reggiano"
                        },
                        new
                        {
                            Id = 25,
                            NameIngredient = "unsalted butter"
                        },
                        new
                        {
                            Id = 26,
                            NameIngredient = "self-raising flour"
                        },
                        new
                        {
                            Id = 27,
                            NameIngredient = "muscovado sugar"
                        },
                        new
                        {
                            Id = 28,
                            NameIngredient = "black treacle"
                        },
                        new
                        {
                            Id = 29,
                            NameIngredient = "golden syrup"
                        },
                        new
                        {
                            Id = 30,
                            NameIngredient = "large eggs"
                        },
                        new
                        {
                            Id = 31,
                            NameIngredient = "milk"
                        },
                        new
                        {
                            Id = 32,
                            NameIngredient = "syrup"
                        },
                        new
                        {
                            Id = 33,
                            NameIngredient = "fine sea salt"
                        },
                        new
                        {
                            Id = 34,
                            NameIngredient = "ground ginger"
                        },
                        new
                        {
                            Id = 35,
                            NameIngredient = "cinnamon"
                        },
                        new
                        {
                            Id = 36,
                            NameIngredient = "bicarbonate of soda"
                        },
                        new
                        {
                            Id = 37,
                            NameIngredient = "icing sugar"
                        },
                        new
                        {
                            Id = 38,
                            NameIngredient = "white chocolate"
                        },
                        new
                        {
                            Id = 39,
                            NameIngredient = "celery sticks"
                        },
                        new
                        {
                            Id = 40,
                            NameIngredient = "rapeseed oil"
                        },
                        new
                        {
                            Id = 41,
                            NameIngredient = "carrots"
                        },
                        new
                        {
                            Id = 42,
                            NameIngredient = "bay leaves"
                        },
                        new
                        {
                            Id = 43,
                            NameIngredient = "thyme"
                        },
                        new
                        {
                            Id = 44,
                            NameIngredient = "tomato purée"
                        },
                        new
                        {
                            Id = 45,
                            NameIngredient = "worcestershire sauce"
                        },
                        new
                        {
                            Id = 46,
                            NameIngredient = "beef stock cubes"
                        },
                        new
                        {
                            Id = 47,
                            NameIngredient = "beef"
                        },
                        new
                        {
                            Id = 48,
                            NameIngredient = "cornflour"
                        },
                        new
                        {
                            Id = 49,
                            NameIngredient = "parsley"
                        },
                        new
                        {
                            Id = 50,
                            NameIngredient = "can black beans"
                        },
                        new
                        {
                            Id = 51,
                            NameIngredient = "bunch coriander"
                        },
                        new
                        {
                            Id = 52,
                            NameIngredient = "flour tortillas"
                        },
                        new
                        {
                            Id = 53,
                            NameIngredient = "avocado or tub guacamole"
                        },
                        new
                        {
                            Id = 54,
                            NameIngredient = "soured cream"
                        },
                        new
                        {
                            Id = 55,
                            NameIngredient = "red or yellow pepper"
                        },
                        new
                        {
                            Id = 56,
                            NameIngredient = "oil"
                        },
                        new
                        {
                            Id = 57,
                            NameIngredient = "red onion"
                        },
                        new
                        {
                            Id = 58,
                            NameIngredient = "chilli powder"
                        },
                        new
                        {
                            Id = 59,
                            NameIngredient = "smoked paprika"
                        },
                        new
                        {
                            Id = 60,
                            NameIngredient = "ground cumin"
                        },
                        new
                        {
                            Id = 61,
                            NameIngredient = "lime"
                        },
                        new
                        {
                            Id = 62,
                            NameIngredient = "ginger"
                        },
                        new
                        {
                            Id = 63,
                            NameIngredient = "tikka curry paste"
                        },
                        new
                        {
                            Id = 64,
                            NameIngredient = "tomatoes"
                        },
                        new
                        {
                            Id = 65,
                            NameIngredient = "light brown soft sugar"
                        },
                        new
                        {
                            Id = 66,
                            NameIngredient = "cardamom pods"
                        },
                        new
                        {
                            Id = 67,
                            NameIngredient = "brown basmati rice"
                        },
                        new
                        {
                            Id = 68,
                            NameIngredient = "ground almonds"
                        },
                        new
                        {
                            Id = 69,
                            NameIngredient = "raw king prawns"
                        },
                        new
                        {
                            Id = 70,
                            NameIngredient = "double cream"
                        },
                        new
                        {
                            Id = 71,
                            NameIngredient = "coriander"
                        });
                });

            modelBuilder.Entity("RecipesApp.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("Serving")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 1575,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "Combine parsley, 2 1/2 tablespoons olive oil, oregano, vinegar, garlic, salt, red pepper flakes, and black pepper in a bowl; mix the chimichurri thoroughly. Place chicken on a cutting board and remove the backbone using kitchen shears. Press down on the breast with the heel of your hand to flatten. Loosen the skin of the chicken carefully and rub the chimichurri underneath, distributing it evenly. Wrap the chicken in plastic wrap and refrigerate for 24 hours. Allow chicken to come to room temperature for no more than 1 hour before baking. Preheat oven to 450 degrees F (230 degrees C). Rub 1 teaspoon olive oil over the chicken; season with salt and pepper. Place onion in a cast-iron skillet. Pour chicken broth over onion. Place seasoned chicken on top. Bake in the preheated oven until no longer pink at the bone and the juices run clear, about 45 minutes. An instant-read thermometer inserted into the thickest part of the meat, near the bone, should read 165 degrees F (74 degrees C). Allow chicken to rest in a warm area for 10 minutes before slicing.",
                            Serving = 6,
                            Title = "Chimichurri Baked Chicken"
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = 600,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "Heat oil in a large pot over medium heat. Cook pancetta until most of fat is rendered out, about 6 minutes. Remove cooked pancetta with a slotted spoon and save. Raise heat to high and transfer meat to the pot. Season with salt. Cook and stir until liquid releases from beef and begins to evaporate, and meat browns, 10 to 15 minutes. Reduce heat to medium-high. Add celery, carrots, reserved cooked pancetta, salt and pepper. Cook and stir about 5 minutes. Add a heaping tablespoon of tomato paste, bay leaf, and white wine. Cook and stir, scraping up the brownings from the bottom of the pan, 2 to 3 minutes. Add sliced onions. Reduce heat to medium. Cover pot and cook 30 minutes without stirring. After 30 minutes, stir onions and meat until well mixed. Cover again, and cook another 30 minutes. Stir. Reduce heat to low and cook uncovered 8 to 10 hours, stirring occasionally. Skim off fat as mixture cooks. If sauce seems to reduce too much, add water or broth as needed to maintain a sauce-like consistency. Cook until beef and onions seem to melt into each other.Bring a large pot of lightly salted water to a boil. Cook rigatoni in the boiling water, stirring occasionally until just barely al dente, 10 to 12 minutes. Drain. Add rigatoni to the sauce and cook until heated through. Serve topped with a pinch of marjoram and freshly grated Parmigiano-Reggiano cheese.",
                            Serving = 8,
                            Title = "Rigatoni alla Genovese"
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = 65,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "Heat the oven to 180C/160C fan/gas 4. Melt 1 tbsp butter in a small pan, then stir in ½ tbsp flour to create a wet paste. Brush it over the inside of a 9-inch bundt tin. Put the remaining butter, sugar, treacle and golden syrup in a pan set over a medium heat and stir until everything has melted together. Leave to cool a little. Pour the mixture into a large bowl and whisk in the eggs and milk. Fold in the stem ginger, remaining flour, salt, ground ginger, cinnamon and bicarb. Tip into the prepared tin and bake for 40-45 mins, or until firm to the touch. Leave to cool for 10 mins in the tin, then turn out onto a wire rack to cool completely. To make the icing, whisk the milk, ginger syrup and icing sugar together. Melt the chocolate in a heatproof bowl in the microwave in 1-min bursts. Leave to cool a little, then whisk into the milk mixture. Spoon the icing over the cake, then decorate with the crystallised ginger pieces.",
                            Serving = 12,
                            Title = "Ginger & white chocolate cake"
                        },
                        new
                        {
                            Id = 4,
                            CookingTime = 260,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "Fry the onion and celery in 1 tbsp oil over a low heat until they start to soften – about 5 mins. Add the carrots, bay and thyme, fry for 2 mins, stir in the purée and Worcestershire sauce, add 600ml boiling water, stir and tip everything into a slow cooker. Crumble over the stock cubes or add the stock pots and stir, then season with pepper (don’t add salt as the stock may be salty). Clean out the frying pan and fry the beef in the remaining oil in batches until it is well browned, then tip each batch into the slow cooker. Cook on low for 8-10 hrs, or on high for 4 hrs. If you want to thicken the gravy, mix the cornflour with a splash of cold water to make a paste, then stir in 2 tbsp of the liquid from the slow cooker. Tip back into the slow cooker, stir and cook for a further 30 mins on high. Stir in the parsley and season again to taste. Serve with mash, if you like. Leave to cool before freezing.",
                            Serving = 12,
                            Title = "Slow-cooker beef stew"
                        },
                        new
                        {
                            Id = 5,
                            CookingTime = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "To make the fajita mix, take two or three strips from each colour of pepper and finely chop them. Set aside. Heat the oil in a frying pan and fry the remaining pepper strips and the onion until soft and starting to brown at the edges. Cool slightly and mix in the chopped raw peppers. Add the garlic and cook for 1 min, then add the spices and stir. Cook for a couple of mins more until the spices become aromatic, then add half the lime juice and season. Transfer to a dish, leaving any juices behind, and keep warm. Tip the black beans into the same pan, then add the remaining lime juice and plenty of seasoning. Stir the beans around the pan to warm them through and help them absorb any flavours of the fajita mix, then stir through the coriander. Warm the tortillas in a microwave or in a low oven, then wrap them so they don’t dry out. Serve the tortillas with the fajita mix, beans, avocado and soured cream for everyone to help themselves.",
                            Serving = 4,
                            Title = "Vegetarian fagitas"
                        },
                        new
                        {
                            Id = 6,
                            CookingTime = 40,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preparation = "Put the onion, ginger and garlic in a food processor and blitz to a smooth paste. Heat the oil in a large flameproof casserole dish or pan over a medium heat. Add the onion paste and fry for 8 mins or until lightly golden. Stir in the curry paste and fry for 1 min more. Add the tomatoes, tomato purée, sugar and cardamom pods. Bring to a simmer and cook, covered, for another 10 mins. Cook the rice following pack instructions. Scoop the cardamom out of the curry sauce and discard, then blitz with a hand blender, or in a clean food processor. Return to the pan, add the almonds and prawns, and cook for 5 mins. Season to taste and stir through the cream and coriander. Serve with the rice and naan breads, if you like.",
                            Serving = 4,
                            Title = "Prawn tikka masala"
                        });
                });

            modelBuilder.Entity("RecipesApp.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("RecipesApp.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesApp.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("RecipesApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesApp.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RecipesApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RecipesApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipesApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RecipesApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
